### ISSUE TITLE
Connection to Mastadon and Memos fails. Only Bluesky works.

### ISSUE THREAD

**Issue by vnl** [dandelionmood/mastodon2memos#1]
Hey, 

Following the instructions, I have created the config file. I get to connect to Bluesky but fail to connect to Mastadon and Memos. 
One thing to note is that I have an nginx proxy manager installed, so I have https://memos.mydomain.com/ as the URL. I created the access token in memos. 

```
$ python cli.py troubleshoot

Reading configuration from: config.yaml

✔ Successfully connected to Bluesky API.
Successfully resolved Bluesky username to user ID: xx:xx:xx

✘ Failed to connect to Memos API: 'id'
```

This is when I have Mastadon on:
```
 $ python cli.py troubleshoot

Reading configuration from: config.yaml

✘ Failed to connect to Mastodon API: Failed to connect to Mastodon API.
```

This is my config.yaml file

```
mastodon:
  # Enable Mastodon integration
  enabled: true

  # Base URL of the Mastodon instance
  api_url: "https://mastodon.social"

  # Client ID for the Mastodon application
  client_id: "my app client id"

  # Client Secret for the Mastodon application
  client_secret: "my app client secret"

  # Access Token for the Mastodon application
  access_token: "my access token for the app"

  # Mastodon user name
  username: "vivianlobo"

bluesky:
  # Enable Bluesky integration
  enabled: true

  # Base URL of the Memos instance
  api_url: "https://bsky.social"

  # Handle for the Bluesky account
  handle: "vivianlobo.bsky.social"

  # Password for the Bluesky account
  password: "my password"

memos:
  # Base URL of the Memos instance
  api_url: "https://xx.mydomain.com"

  # Access Token for the Memos application
  access_token: "super long access token here"
```
